### ISSUE TITLE
pyo3_runtime. PanicException: called 'Result: :unwrap()

### ISSUE THREAD

**Issue by Jacksonmmmn** [henrytirla/Solana-Raydium-Trading#6]
i got that error
```
note: run with 'RUST_BACKTRACE=1 environment variable to display a backtrace
Traceback (most recent call last):
File "main.py", line 54, in 
asyncio.run (start_buy (payer, valance, client))
File " /us/local/lib/python3.7/asyncio/runners.py", line 43, in run
return loop.run_until_complete (main)
File "/us/local/lib/python3.7/asyncio/base_events.py", line 566, in run_until_complete self.run_forever ()
File "/us/local/lib/python3.7/asyncio/base_events-py", line 534, in run_ forever self._run_once ()
File " /us/local/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
handle. _run ()
File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "main.py", line 20, in start_buy
buy_transaction=await buy (client, manny, payer, amount-0.02) #Enter amount of sol you wish to saand File "/workspace/contrader /buy_swap.py", line 80, in buy
E501 line too long (91 > 79 characters) | visual indent
txn = solana_client.send_transaction (swap_tx, payer, Wsol_account_keyPair)
File "/usr/local/lib/python3.7/site-packages/solana/rpc/api.py",line1067,insend_transaction
txn_resp = self.send_raw_transaction(txn.serialize() , opts=opts_to_use)
File "/us/local/lib/python3.7/site-packages/solana/rpc/api.py",line992,insend_raw_transaction
resp = self._provider.make_request (body, SendTransactionResp)
File " /us/local/lib/python3.7/site-packages/solana/exceptions.py", line 43, in argument_decorator return func (*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/solana/rpc/providers/http.py",line49,in make_request return _parse_raw(raw, parser=parser)
File "/usr/local/lib/python3.7/site-packages/solana/rpc/providers/core.py",line95,in_parse_raw
parsed = parser. from_json (raw) # type: ignore
pyo3_runtime. PanicException: called 'Result: :unwrap() on an 'Err' value: Error ("missing field 'data'", line: 0, column: 0)
```

I think it comes make_swap_instruction function

do you have any idea with this?

**Comment by henrytirla** [comment]
Make sure you create a wrap sol token and fund it before using wrap sol scripts. Buys and sells occur only via Sol token account

**Comment by Jacksonmmmn** [comment]
> Make sure you create a wrap sol token and fund it before using wrap sol scripts. Buys and sells occur only via Sol token account

I never change your code. How can i fix it?

**Comment by henrytirla** [comment]
Dm on tg if you want my personal assistance it will cost you a fee
